### get all tweets
GET http://localhost:3000/tweet/3

### create tweet
POST http://localhost:3000/tweet
Content-Type: application/json

{
  "text": "This is the tweet number x",
  "image": "https://example.com/image.jpg",
  "userId": 3,
  "hashtags": [2, 5]
}
