### Get all user
GET http://localhost:8080/users

### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
    "firstName": "Mustafa",
    "lastName": "Khaled",
    "gender": "Male",
    "email": "mustafa.khaled@gmail.com",
    "password": "12345678"
}

