### Get all user
GET http://localhost:3000/users

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "mariam",
    "email": "mariam.t@gmail.com",
    "password": "12345678",
      "profile": {
        "firstName": "mariam",
        "lastName": "Taha",
        "gender": "Female",
        "dateOfBirth": "2000-01-01",
        "bio": "Hello, I'm mariam",
        "profileImage": "https://example.com/sarah.jpg"
    }
}

### Delete user
DELETE http://localhost:3000/users/4